### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by Tealk** [criticalAY/Neer#9]
###### Reproduction Steps

1. Start the app

###### Expected Result

App starts

###### Actual Result

App crash

###### Debug info

CraphenOS
V1.02.0

```
type: crash
osVersion: google/oriole/oriole:14/AP1A.240305.019.A1/2024031400:user/release-keys
package: com.criticalay.neer:10200300
process: com.criticalay.neer
processUptime: 655 + 196 ms
installer: dev.imranr.obtainium

java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number. Expected identity hash: e605a51f33781baa034dfbf0cf4a7aad, found: ed18e4355d6044d536f6ad5bb8d89183
	at B.l.l(SourceFile:94)
	at r1.f.onOpen(SourceFile:16)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:434)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:323)
	at r1.f.c(SourceFile:5)
	at r1.f.e(SourceFile:64)
	at r1.f.a(SourceFile:24)
	at r1.g.k(SourceFile:10)
	at com.criticalay.neer.data.NeerDatabase.m(SourceFile:13)
	at e1.a.L(SourceFile:1)
	at A1.f.call(SourceFile:154)
	at n1.b.q(SourceFile:81)
	at m2.a.n(SourceFile:9)
	at D2.F.run(SourceFile:97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: I2.g: [m0{Cancelling}@c57aee1, Dispatchers.Main.immediate]
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release

**Comment by criticalAY** [comment]
Could you check with the latest release if it is fixed or not. I just updated the code and the release

**Comment by criticalAY** [comment]
I need someone to manage the releases and branches, a maintainer basically

**Comment by Tealk** [comment]
App ist staring again
